apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: kyverno-critical
value: 1000000000
preemptionPolicy: PreemptLowerPriority
globalDefault: false
description: "Used for critical Kyverno components, prioritized just below system-critical"
